### ISSUE TITLE
RuntimeError: each element in list of batch should be of equal size

### ISSUE THREAD

**Issue by liuzh00** [zhaicao/DAGCN-ABSA#1]
作者您好，可以提供一份absa_parser文件吗

**Comment by liuzh00** [comment]
F:\miniconda3\envs\OpenPrompt\python.exe D:/Code/DAGCN-ABSA-master/train.py
Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.predictions.decoder.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
F:\miniconda3\envs\OpenPrompt\lib\site-packages\torch\nn\modules\rnn.py:67: UserWarning: dropout option adds dropout after all but last recurrent layer, so non-zero dropout expects num_layers greater than 1, but got dropout=0.1 and num_layers=1
  warnings.warn("dropout option adds dropout after all but last "
cuda memory allocated: 498350592
n_trainable_params: 122184580, n_nontrainable_params: 0
training arguments:
>>> model: dagcnbert
>>> best_model: None
>>> type: train
>>> dataset: laptop
>>> optimizer: <class 'torch.optim.adam.Adam'>
>>> initializer: <function xavier_uniform_ at 0x000001B6B34D33A0>
>>> lr: 0.002
>>> l2reg: 0.0001
>>> num_epoch: 70
>>> batch_size: 16
>>> log_step: 5
>>> embed_dim: 300
>>> post_dim: 30
>>> pos_dim: 30
>>> dep_dim: 100
>>> deppost_dim: 30
>>> hidden_dim: 50
>>> polarities_dim: 3
>>> num_layers: 2
>>> input_dropout: 0.7
>>> gcn_dropout: 0.5
>>> layer_dropout: 0
>>> lower: True
>>> gat_alpha: 0.1
>>> direct: False
>>> loop: True
>>> aggr_neighbor_method: lstm
>>> aggr_neighbor_dropout: 0.1
>>> aggr_hidden_method: concat
>>> bidirect: True
>>> rnn_hidden: 50
>>> rnn_layers: 1
>>> rnn_dropout: 0.1
>>> attention_heads: 2
>>> num_deprel_heads: 10
>>> attn_layers: 1
>>> att_dropout: 0.1
>>> top_k: 6
>>> deprel_alpha: 0
>>> pretrained_bert_name: bert-base-uncased
>>> adam_epsilon: 1e-08
>>> bert_dim: 768
>>> bert_dropout: 0.1
>>> weight_decay: 0.0
>>> diff_lr: False
>>> bert_lr: 2e-05
>>> max_length: 85
>>> patience: 30
>>> device: cuda
>>> seed: 283
>>> vocab_dir: ./dataset/Restaurants
>>> glove_dir: ./glove/glove.840B.300d.txt
>>> pad_id: 0
>>> parseadj: False
>>> parsehead: False
>>> cuda: 0
>>> pooling: avg
>>> output_merge: biaffine
>>> losstype: None
>>> alpha: 1
>>> beta: 1
>>> model_class: <class 'models.dagcn_bert.DAGCNBert'>
>>> dataset_file: {'train': './dataset/Laptops/train.json', 'valid': './dataset/Laptops/valid.json', 'test': './dataset/Laptops/test.json'}
>>> inputs_cols: ['text_bert_indices', 'bert_segments_ids', 'attention_mask', 'asp_start', 'asp_end', 'src_mask', 'aspect_mask', 'text', 'head', 'length', 'deprel']
>>> dep_size: 43
bert learning rate on
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
epoch: 1
F:\miniconda3\envs\OpenPrompt\lib\site-packages\transformers\optimization.py:306: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
Traceback (most recent call last):
  File "D:\Code\DAGCN-ABSA-master\train.py", line 456, in <module>
    main()
  File "D:\Code\DAGCN-ABSA-master\train.py", line 448, in main
    ins.run()
  File "D:\Code\DAGCN-ABSA-master\train.py", line 262, in run
    max_valid_acc, max_valid_f1, model_path, checkpoint = self._train(criterion, optimizer)
  File "D:\Code\DAGCN-ABSA-master\train.py", line 169, in _train
    for i_batch, sample_batched in enumerate(self.train_dataloader):
  File "F:\miniconda3\envs\OpenPrompt\lib\site-packages\torch\utils\data\dataloader.py", line 628, in __next__
    data = self._next_data()
  File "F:\miniconda3\envs\OpenPrompt\lib\site-packages\torch\utils\data\dataloader.py", line 671, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "F:\miniconda3\envs\OpenPrompt\lib\site-packages\torch\utils\data\_utils\fetch.py", line 61, in fetch
    return self.collate_fn(data)
  File "F:\miniconda3\envs\OpenPrompt\lib\site-packages\torch\utils\data\_utils\collate.py", line 265, in default_collate
    return collate(batch, collate_fn_map=default_collate_fn_map)
  File "F:\miniconda3\envs\OpenPrompt\lib\site-packages\torch\utils\data\_utils\collate.py", line 128, in collate
    return elem_type({key: collate([d[key] for d in batch], collate_fn_map=collate_fn_map) for key in elem})
  File "F:\miniconda3\envs\OpenPrompt\lib\site-packages\torch\utils\data\_utils\collate.py", line 128, in <dictcomp>
    return elem_type({key: collate([d[key] for d in batch], collate_fn_map=collate_fn_map) for key in elem})
  File "F:\miniconda3\envs\OpenPrompt\lib\site-packages\torch\utils\data\_utils\collate.py", line 139, in collate
    raise RuntimeError('each element in list of batch should be of equal size')
RuntimeError: each element in list of batch should be of equal size

Process finished with exit code 1
请问这个问题改如何处理？期待您的回复！！
